In [2]:
from feature_selection_and_model_creation import RFE_reg

In [3]:
import pandas as pd

In [4]:
dataset = pd.read_csv(
            r"D:\python\Machine Learning and Data Science Capstone Project\2.Data preprocessing\cleaned_saas_sales.csv"
        )

In [5]:
dataset

,Country,City,Region,Subregion,Customer,Industry,Segment,Product,Sales,Quantity,Discount,Profit,Year,Month,Day
0,Ireland,Dublin,EMEA,UKIR,Chevron,Energy,SMB,Marketing Suite,261.9600,2.0,0.00,41.9136,2022,11,9
1,Ireland,Dublin,EMEA,UKIR,Chevron,Energy,SMB,FinanceHub,731.9400,3.0,0.00,219.5820,2022,11,9
2,United States,New York City,AMER,NAMER,Phillips 66,Energy,Strategic,FinanceHub,14.6200,2.0,0.00,6.8714,2022,6,13
3,Germany,Stuttgart,EMEA,EU-WEST,Royal Dutch Shell,Energy,SMB,ContactMatcher,957.5775,5.0,0.45,-383.0310,2021,10,11
4,Germany,Stuttgart,EMEA,EU-WEST,Royal Dutch Shell,Energy,SMB,Marketing Suite - Gold,22.3680,2.0,0.20,2.5164,2021,10,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Germany,Hamburg,EMEA,EU-WEST,Johnson & Johnson,Healthcare,SMB,SaaS Connector Pack,25.2480,3.0,0.20,4.1028,2020,1,22
9990,United States,Milwaukee,AMER,NAMER,American Express,Finance,SMB,SaaS Connector Pack,91.9600,2.0,0.00,15.6332,2023,2,27
9991,United States,Milwaukee,AMER,NAMER,American Express,Finance,SMB,Site Analytics,258.5760,2.0,0.20,19.3932,2023,2,27
9992,United States,Milwaukee,AMER,NAMER,American Express,Finance,SMB,Support,29.6000,4.0,0.00,13.3200,2023,2,27
9993,United States,Dallas,AMER,NAMER,Comcast,Communications,SMB,OneView,243.1600,2.0,0.00,72.9480,2023,5,5

In [6]:
RFE_reg.Result()

============================================================
Running RFE using LinearRegression
============================================================
X_train_rfe shape: (7495, 20)
X_test_rfe shape : (2499, 20)

Selected Features:
cat__City_Berlin
cat__City_Glasgow
cat__City_Manila
cat__City_Marseille
cat__City_Moscow
cat__City_Osaka
cat__City_Paris
cat__City_Tijuana
cat__City_Toronto
cat__Subregion_NAMER
cat__Customer_Allstate
cat__Customer_Valero Energy
cat__Product_Alchemy
cat__Product_Big Ol Database
cat__Product_ContactMatcher
cat__Product_FinanceHub
cat__Product_Marketing Suite
cat__Product_Marketing Suite - Gold
remainder__Sales
remainder__Discount

============================================================
Running RFE using LinearSVR
============================================================
X_train_rfe shape: (7495, 20)
X_test_rfe shape : (2499, 20)

Selected Features:
cat__City_Burlington
cat__City_Donetsk
cat__City_Glasgow
cat__City_Hordaland
cat__City_Marseille
cat__City_Minneapolis
cat__City_Puerto Vallarta
cat__City_Turin
cat__Subregion_NAMER
cat__Product_Alchemy
cat__Product_Big Ol Database
cat__Product_ChatBot Plugin
cat__Product_ContactMatcher
cat__Product_FinanceHub
cat__Product_Marketing Suite
cat__Product_Marketing Suite - Gold
cat__Product_Site Analytics
remainder__Sales
remainder__Quantity
remainder__Discount

============================================================
Running RFE using DecisionTreeRegressor
============================================================
X_train_rfe shape: (7495, 20)
X_test_rfe shape : (2499, 20)

Selected Features:
cat__City_Tijuana
cat__City_Tokyo
cat__City_Toronto
cat__Region_APJ
cat__Subregion_NAMER
cat__Subregion_UKIR
cat__Industry_Healthcare
cat__Industry_Transportation
cat__Segment_SMB
cat__Product_Alchemy
cat__Product_Big Ol Database
cat__Product_ContactMatcher
cat__Product_Marketing Suite - Gold
cat__Product_Support
remainder__Sales
remainder__Quantity
remainder__Discount
remainder__Year
remainder__Month
remainder__Day

============================================================
Running RFE using RandomForestRegressor
============================================================
X_train_rfe shape: (7495, 20)
X_test_rfe shape : (2499, 20)

Selected Features:
cat__Country_Germany
cat__Country_Mexico
cat__City_Berlin
cat__City_Osaka
cat__City_Paris
cat__City_Tijuana
cat__Region_EMEA
cat__Subregion_JAPN
cat__Subregion_NAMER
cat__Customer_Allstate
cat__Product_Alchemy
cat__Product_Big Ol Database
cat__Product_ContactMatcher
cat__Product_Support
remainder__Sales
remainder__Quantity
remainder__Discount
remainder__Year
remainder__Month
remainder__Day

FINAL RESULTS:

                        Linear LinearSVR     SVMnl  Decision    Random
RFE_LinearRegression  0.350849  0.304189  0.023302  0.833475  0.795536
RFE_LinearSVR         0.359584  0.305325  0.030331  0.744362  0.811495
RFE_DecisionTree      0.359844  0.304215   0.01748    0.7199  0.762648
RFE_RandomForest      0.354605  0.301579  0.023156  0.744063  0.780752

Best RFE Method : RFE_LinearRegression
Best Model : Decision
Best R2 : 0.8334745649104331

                        Linear LinearSVR     SVMnl  Decision    Random
RFE_LinearRegression  0.350849  0.304189  0.023302  0.833475  0.795536
RFE_LinearSVR         0.359584  0.305325  0.030331  0.744362  0.811495
RFE_DecisionTree      0.359844  0.304215   0.01748    0.7199  0.762648
RFE_RandomForest      0.354605  0.301579  0.023156  0.744063  0.780752